version: "3.7"

services:
    app:
        container_name: app-a7
        build:
            context: ../
            dockerfile: deployments/Dockerfile
        ports:
            - "10007:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ".:/app"
            - "/app/node_modules"
        restart: always
