version: "2"
services:
  app:
    container_name: app-a2
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      A2_DATABASE_USER: user
      A2_DATABASE_PASSWORD: pass
      A2_DATABASE_HOST: db
      A2_DATABASE_NAME: A2
      A2_JWT_PRIVKEY: -----BEGIN EC PRIVATE KEY-----
        MHQCAQEEIIcpb0EzAbE7DdGZbQpsvNta19PGqviOOCyG+jGEgvjDoAcGBSuBBAAK
        oUQDQgAEF7e2wIV/9VfHvUc8gD7mkBmsrjWCSpLHO1CJWhdcShdc6biRrIJ4kKHU
        A7Na7FOW6y7Ul4pckXprsvSOqGdClg==
        -----END EC PRIVATE KEY-----
      A2_JWT_PUBKEY: -----BEGIN PUBLIC KEY-----
        MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEF7e2wIV/9VfHvUc8gD7mkBmsrjWCSpLH
        O1CJWhdcShdc6biRrIJ4kKHUA7Na7FOW6y7Ul4pckXprsvSOqGdClg==
        -----END PUBLIC KEY-----
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "10002:10002"
    networks:
      - a2_net
    volumes:
      - "../app/:/app"
    restart: always

  db:
    container_name: db-a2
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: A2
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - a2_net
    volumes:
      - storage-a2-database:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d

volumes:
  storage-a2-database:

networks:
  a2_net:
