version: "2"
services:
  app:
    container_name: app-a8
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      A8_ADMIN_USERNAME: ${A8_ADMIN_USERNAME}
      A8_ADMIN_PASSWORD: ${A8_ADMIN_PASSWORD}
      A8_DEBUG: ${A8_DEBUG}
      A8_SECRET_KEY: ${A8_SECRET_KEY}
    volumes:
      - "../app/:/app"
    ports:
      - "5000:5000"
      - "9051:9051"
    networks:
      - a8_net
    restart: always

networks:
  a8_net:
