version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: a2_insecure_api
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports:
            - "10002:10002"
        environment:
            MONGO_PASSWORD: svGX8SViufvYYNu6m3Kv
            MONGO_USER: u_insecure_go_project
            MONGO_DBNAME: insecure_go_project
            MONGO_HOST: mongodb
        networks:
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net
