version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: a2_insecure_api
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports:
            - "10002:10002"
        networks:
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        environment:
            MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo_user
            MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo_pass
            MONGO_INITDB_DATABASE: /run/secrets/mongo_db
        secrets:
          - mongo_pass
          - mongo_user
          - mongo_db

        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net
            
secrets:
    mongo_pass:
        external: true
    mongo_user:
        external: true
    mongo_db: 
        external: true