version: "3.4"
services:
  app:
    container_name: app-a2
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      A2_DATABASE_USER: user
      A2_DATABASE_PASSWORD: pass
      A2_DATABASE_HOST: db
      A2_DATABASE_NAME: A2
    env_file:
            - ../app/.env
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "10002:10002"
    networks:
      - a2_net
    volumes:
      - "../app/:/app"
    restart: always

  db:
    container_name: db-a2
    image: mariadb:10.6.3
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: A2
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - a2_net
    volumes:
      - storage-a2-database:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
        - a2_net

volumes:
  storage-a2-database:

networks:
  a2_net: