version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: snake_pro_a3
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports:
            - "10033:10033"
        environment:
          SECRET_KEY: secret-key
        networks:
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb
        environment:
            SALT: ${SALT}


    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net

    proxy: 
        image: fsouza/docker-ssl-proxy
        container_name: production_nginx
        volumes:
            - ./certs/:/etc/nginx/certs/
        ports:
            - 8080:8080
            - 443:443
        networks:
            - insecure_net
        environment:
            DOMAIN: localhost
            TARGET_PORT: 10033
            TARGET_HOST: snake_pro_a3
            SSL_PORT: 443
        depends_on:
            - api