version: "3.7"

services:
    hello-world:
        container_name: comment-killer
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 10007:10007
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
