version: '3'

services:

  apache-php:
    container_name: a1_apache_php
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    ports:
      - '10001:80'
    restart: always
    environment:
      DB_PASSWORD: userpassword
      DB_DATABASE: a1db
      DB_USER: user
      DB_HOST: mysqldb
      DB_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - a1net
    volumes:
      - ../app:/var/www/html

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: a1db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
        - a1net
    volumes:
        - db_data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/schema.sql:ro

networks:
    a1net:

volumes:
    db_data:
