version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
        command: --init-file /data/application/init.sql
        volumes:
          - ../app/init.sql:/data/application/init.sql
        working_dir: ../app
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=imd
          - MYSQL_DATABASE=login_1
          - MYSQL_USER=root
          - MYSQL_PASSWORD=imd
        ports:
          - "3308:3306"
  website:
    container_name: php72
    build:
      context: ./
    links:
      - "mysql:database"
    volumes:
      - ../app:/var/www/html
    ports:
      - 1001:80
    depends_on:
      - mysql
