version: '3.3'

services:
  drupal:
    image: drupal:7.58
    container_name: drupal
    build:
      context: ../
      dockerfile: deployments/drupal.Dockerfile
    ports:
      - 80:80
    volumes:
      - ../app/html/modules:/var/www/html/modules
      - ../app/html/profiles:/var/www/html/profiles
      - ../app/html/sites/:/var/www/html/sites
      - ../app/html/themes:/var/www/html/themes
    restart: always
    networks: 
      - a9_net

  db:
    image: postgres:latest
    container_name: a9db
    ports:
      - 5432:5432
    networks: 
      - a9_net
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../app/dump.db:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data:

networks: 
  a9_net:
