name: Test action
on:
  pull_request:
    branches:
        - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test action on current repository
        id: scan
        uses: ./
        with:
          secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
          minimum-severity: 'MEDIUM'
          post-scan-status-comment: true
          post-sast-review-comments: true
          fail-on-sast-scan: true
